docker-build:
	docker-compose build

docker-start:
	docker-compose up -d

docker-stop:
	docker-compose down --remove-orphans --volumes

docker-clean:
	docker rmi airflow_flower airflow_airflow-init airflow_airflow-scheduler airflow_airflow-webserver airflow_airflow-worker



